<?php

//define — Defines a named constant
DEFINE('DB_USER', 'root');
DEFINE('DB_PASSWORD', 'root');
DEFINE('DB_HOST', 'localhost');
DEFINE('DB_NAME', 'school');

$dbc = @mysqli_connect(DB_HOST, DB_USER, DB_PASSWORD, DB_NAME)
        or die('Could not connect to MySQL ' .
                mysqli_connect_error());

/*
PHP supports one error control operator: the at sign (@). 
 * When prepended to an expression in PHP, any error messages that might be 
 * generated by that expression will be ignored. */